spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/netzgrafikeditor
  jooq:
    sql-dialect: Postgres
  flyway:
    enabled: true
    fail-on-missing-locations: true
    locations: classpath:db/migration
  datasource:
    driver-class-name: org.postgresql.Driver
    username: netzgrafikeditor
    password: netzgrafikeditor
    url: jdbc:postgresql://postgres/netzgrafikeditor


endpoints:
  web:
    cors:
      path-mappings: /**
      allowed-origins: "*"
      allowed-methods: GET, POST, PUT, DELETE
      allowed-headers: "*"

logging:
  level:
    org.springframework: INFO

auth:
  audience:
    service-name: fc44839c-e95f-4854-a52d-449867a9aa62

# only active in 'local' profile
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
  oAuthFlow:
    authorizationUrl: http://localhost:8081/realms/netzgrafikeditor/protocol/openid-connect/auth
    tokenUrl: http://localhost:8081/realms/netzgrafikeditor/protocol/openid-connect/token